[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/v3-per/=lib/v3-periphery/",
    "forge-std/=lib/forge-std/src/",
]

[lint]
enabled = true
lints = ["unsafe-typecast"]

[rpc_endpoints]
MAINNET_RPC_URL = "$MAINNET_RPC_URL"
SEPOLIA_RPC_URL = "$SEPOLIA_RPC_URL"

[profile.aidan]
sender = "0x31fdeb452632cb502bf145b275e0f0d98c4732d6"
tx_origin = "0x31fdeb452632cb502bf145b275e0f0d98c4732d6"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
